api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    resources :todos
    resources :users do
      member do
        get :confirmation
        get :issue_token
        get :unlock
      end
      collection do
        get :loginform
        post :login, :logout
        post :send_email
        post :reset_password
      end
    end
  end
  
end

api/app/models/user.rb
require "securerandom"

class User < ApplicationRecord
  has_secure_password(:password, validations: true)
  has_many :todos, dependent: :destroy

  validates :name, presence: true,  length: { minimum: 3 }

  PASS_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[!-\/:-@\[-`{-~])[!-~]{8,100}+\z/i
  validates :password,  presence: true, 
                        length: { minimum: 8 }, 
                        format: { with: PASS_REGEX, message: 'は半角英小文字、大文字、数字、記号が最低でも1文字必要です。' },
                        allow_nil: true,
                        on: :create

  validates :password,  presence: true, 
                        length: { minimum: 8 }, 
                        format: { with: PASS_REGEX, message: 'は半角英小文字、大文字、数字、記号が最低でも1文字必要です。' },
                        allow_nil: true,
                        if: :reset?

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, { 
                      presence: true, 
                      format: { with: VALID_EMAIL_REGEX, message: 'はメールの形式ではありません' },
                      uniqueness: { case_sensitive: false },
                    }

  before_create :ensure_token
  after_create :send_confirmation_email
  before_save { self.email = email.downcase }

  def unlock(params)
    self.unlock_token == params[:unlock_token]
    self.locked_at = nil
    save
  end

  def confirmation(params)
    if self.is_confirmed
      return true, nil
    elsif self.confirmation_sent_at < 30.minutes.ago
      return false, "期限切れです。"
    elsif self.confirmation_token != params[:confirmation_token]
      return false, "不正なトークンが指定されました。"
    else
      self.is_confirmed = true
      return save, nil
    end
  end

  def issue_confirmation_token
    self.confirmation_token = generate_token(:confirmation_token)
    if save
      send_reconfirmation_email
    end
  end

  def increment_failed_attempts
    increment!(:failed_attempts)
    if failed_attempts >= 5
      self.locked_at = DateTime.current.in_time_zone
      self.failed_attempts = 0
      self.unlock_token = generate_token(:unlock_token)
      save
      send_unlock_email
    end
  end

  def send_reset_password
    self.reset_password_token = generate_token(:reset_password_token)
    reset_password_email if save
  end

  def clean_up_reset_column!
    reset_password_token = nil
    reset_password_sent_at = nil
    save!
  end

  def gwt_token!
    payload = { token: authentication_token }
    hmac_secret = Rails.application.credentials.secret_key_base
    # payloadを、hmac_secret(秘密鍵)でHS256アルゴリズムで署名する
    token = JWT.encode(payload, hmac_secret, 'HS256', { typ: 'JWT' })
    {
      id: self.id,
      name: self.name,
      email: self.email,
      authentication_token: token,
    }
  end

  private
  def send_reconfirmation_email
    UserMailer.reconfirmation_email(self).deliver_later
  end

  def send_confirmation_email
    UserMailer.confirmation_email(self).deliver_later
  end

  def send_unlock_email
    UserMailer.unlock_email(self).deliver_later
  end

  def reset_password_email
    UserMailer.reset_password_email(self).deliver_later
  end

  def reset?
    reset_password_token && reset_password_sent_at
  end


  def ensure_token
    if authentication_token.blank? || confirmation_token.blank?
      self.authentication_token = generate_token(:authentication_token)
      self.confirmation_token = generate_token(:confirmation_token)
    end
  end

  def generate_token(key)
    loop do
      token = SecureRandom.uuid
      break token unless User.where(key => token).first
    end
  end

  def self.reset_password(params)
    token = params[:reset_password_token].presence
    user = token && find_by(reset_password_token: token)
    if user && user.reset_password_sent_at > 30.minutes.ago
      if params[:password].blank?
        user.errors.add(:password, 'を入力してください') 
        return false, user
      else
        user.password = params[:password]
        user.password_confirmation = params[:password_confirmation]
        return user.save, user
      end
    else
      user = new
      user.errors.add(:password, 'は制限時間が過ぎています。再度メールを送信してください')
      return false, user
    end
  end

  def self.send_reset_email(params)
    user_email = params[:user][:email].presence
    user = user_email && find_by(email: user_email)
    if user
      user.send_reset_password
      true
    else
      false
    end
  end

  def self.auth_gwt_token(token)
    hmac_secret = Rails.application.credentials.secret_key_base
    decoded_token = JWT.decode(token, hmac_secret, true, { algorithm: 'HS256' })
    self.find_by(authentication_token: decoded_token[0]["token"])
  rescue JWT::VerificationError
    nil
  end

  def self.authenticate_user_from_token(params, token)
    user_email = params[:user_email].presence
    user = user_email && find_by(email: user_email)
    if user && user.locked_at && user.locked_at > 30.minutes.ago
      # アカウントロックされている
      return false, nil, errors: ['acount locked']
    elsif user && (user == self.auth_gwt_token(token))
      return true, user, nil
    else
      user&.increment_failed_attempts
      return false, nil, errors: ['invalid token or email']
    end
  end

  def self.login(params)
    user = find_by(email: params[:email])

    if user.nil?
      # メールアドレスで User が特定出来なかった
      return false, nil, errors: ['メールアドレスまたはパスワードが間違っています']
    elsif user.locked_at && user.locked_at > 30.minutes.ago
      # アカウントロックされている
      return false, nil, errors: ['アカウントがロックされています。メールを確認ください']
    elsif !user.authenticate(params[:password])
      # パスワードが合わない
      user.increment_failed_attempts
      return  false, nil, errors: ['メールアドレスまたはパスワードが間違っています']
    elsif !user.is_confirmed
      return false, nil, errors: ['メールを確認してユーザー登録を完了してください']
    else
      return true, user, nil
    end
  end
end

api/app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: [:login]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :confirmation, :issue_token, :unlock]
  prepend_before_action :authenticate_user_from_token!, except: [:logout, :login, :loginform, :issue_token, :confirmation, :create, :unlock, :send_email, :reset_password]

  # POST
  def reset_password
    u_params = params.require(:user).permit(:reset_password_token, :password, :password_confirmation)
    success, user = User.reset_password(u_params)
    if success
      user.clean_up_reset_column!
      render json: { success: true, user: user }
    else
      render json: { success: false, errors: user.errors }, status: :unprocessable_entity
    end
  end

  # POST
  def send_email
    if User.send_reset_email(params)
      render json: { success: true }
    else
      render json: { success: false }, status: 401
    end
  end

  # GET
  def issue_token
    @user.issue_confirmation_token
  end

  # GET
  def unlock
    if @user.unlock(params)
      redirect_to "#{FRONT_URL}login"
    else
    end
  end

  # GET
  def confirmation
    success, error = @user.confirmation(params)
    if success
      redirect_to "#{FRONT_URL}login"
    else
      @error = error
    end
  end

  # GET
  def loginform
    @user = User.new
  end

  # POST
  def logout
    # session[:user_id] = nil
    
    respond_to do |format|
      format.html { redirect_to users_loginform_path, notice: 'logout' }
      format.json { render json: { success: true } }
    end
  end

  # POST
  def login
    login_params = params.require(:user).permit(:email, :password)
    success, user, errors = User.login(login_params)
    if success
      csrf_token = form_authenticity_token
      # session[:csrf_token] = csrf_token # ???
      # session[:user_id] = user.id
  
      respond_to do |format|
        format.html { redirect_to user, notice: 'login success' }
        format.json { render json: { success: true, csrf: csrf_token, user: user.gwt_token! } }
      end
    else
      render json: errors, status: 401
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: { errors: @user.errors }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

api/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

api/app/views/users/confirmation.html.erb
<h1>ユーザー登録が完了していません</h1>
<%= @error %>
<%= link_to '再度メールを送信する', issue_token_user_url(@user) %>

api/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

api/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
      <th>Authentication token</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= user.authentication_token %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'ログインフォーム', loginform_users_path %>

api/app/views/users/issue_token.html.erb
<h1>まだユーザー登録は完了していません</h1>
<p>ユーザー登録を再発行しました。</p>
<p>メールを確認してユーザー登録を完了してください。</p>

api/app/views/users/loginform.html.erb
<h1>Login User</h1>


<%= form_for(@user, url: login_users_path) do |form| %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to 'Back', users_path %>

api/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

api/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>