api/config/routes.rb
Rails.application.routes.draw do
  scope :api do
    resources :todos
    resources :users do
      member do
        get :confirmation
        get :issue_token
        get :unlock
      end
      collection do
        get :loginform
        post :login, :logout
        post :send_email
        post :reset_password
      end
    end
  end
  
end

api/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 5 },
                      uniqueness: { :scope => :user_id }
  validates :due_on, presence: true

  def late?
    due_on.in_time_zone <= Date.current.in_time_zone
  end
end

api/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  prepend_before_action :authenticate_user_from_token!

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(user_id: @user.id)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = @user.id
    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: { errors: @todo.errors }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      @todo.content = todo_params[:content]
      @todo.due_on = todo_params[:due_on]
      @todo.finished = todo_params[:finished]
      @todo.user_id = @user.id
      
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: { errors: @todo.errors }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { render :show, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :due_on, :finished)
    end
end

api/app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :due_on %>
    <%= form.date_select :due_on %>
  </div>

  <div class="field">
    <%= form.label :finished %>
    <%= form.check_box :finished %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

api/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

api/app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Due on</th>
      <th>Finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.content %></td>
        <td><%= todo.due_on %></td>
        <td><%= todo.finished %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

api/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

api/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Due on:</strong>
  <%= @todo.due_on %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @todo.finished %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>